version: 2.1

commands:
  go-build:
    parameters:
      os:
        description: Target operating system
        type: enum
        enum: ["linux", "darwin"]
        default: "linux"
      arch:
        description: Target architecture
        type: enum
        enum: ["386", "amd64"]
        default: "amd64"
    steps:
      ## don't use CGO so that this binary can run in alpine-linux containers
      - run:
          name: "Build << parameters.os >> << parameters.arch >> binary"
          command: |
            GOOS=<< parameters.os >> \
            GOARCH=<< parameters.arch >> \
            CGO_ENABLED=0 \
            go build -ldflags "-X main.Version=${CIRCLE_TAG}" \
            -o $GOPATH/bin/lights-camera-action-<< parameters.os >>-<< parameters.arch >>

jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run: go test ./...
      - go-build:
          os: linux
          arch: "386"
      - go-build:
          os: linux
          arch: amd64
      - go-build:
          os: darwin
          arch: amd64
      - run: mkdir -v artifacts; cp -v $GOPATH/bin/lights-camera-action-* artifacts/
      - run: tar -cvf artifacts/lights-camera-action.tar artifacts/lights-camera-action-*
      - persist_to_workspace:
          root: artifacts
          paths:
            - lights-camera-action.tar
      - store_artifacts:
          path: artifacts/
  publish:
    docker:
      - image: cibuilds/github:0.12.1
    steps:
      - attach_workspace:
          at: artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "about to publish to tag ${CIRCLE_TAG}"
            tar -xvf artifacts/lights-camera-action.tar
            ls -l *
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/lights-camera-action-linux-386
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/lights-camera-action-linux-amd64
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./artifacts/lights-camera-action-darwin-amd64

workflows:
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/